### ISSUE TITLE
Avoid duplicated citation warnings

### ISSUE THREAD

**Issue by jwallwork23** [pyroteus/pyroteus.github.io#9]
Building the documentation gives the following warnings:
```
docs/source/goalie.rst:116: WARNING: duplicate citation for key "Barral:2016"
docs/source/goalie.rst:116: WARNING: duplicate citation for key "CPB:13"
docs/source/goalie.rst:116: WARNING: duplicate citation for key "Cle:75"
docs/source/goalie.rst:116: WARNING: duplicate citation for key "LDA:10"
docs/source/goalie.rst:116: WARNING: duplicate citation for key "PPP+:06"
docs/source/goalie.rst:116: WARNING: duplicate citation for key "VVP+:92"
```

**Comment by acse-ej321** [comment]
@jwallwork23 I started a new branch to address this issue, but am having difficulty generating the same warnings related to building the documentation. What steps or commands from the Makefile are you using?

**Comment by jwallwork23** [comment]
Make sure you have the latest changes and then `cd docs && make html`.

**Comment by acse-ej321** [comment]
@jwallwork23 I think I have 2 potential ways to resolve this, and also #11, though they are a bit different from each other:

1)  Add unique labels for each module following [bibtex documentation](https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#section-key-prefixing) 
- removes the need to force the addition of the reference sections for each module API page
- required that the references in the module repositories themselves be modified with prefixes
- allows for only shared references by locally specifying unique citation and label prefixes (warnings generated for both these cases if not)

2) Create a separate references.rst with the References section and add a link to it from each module API page 
- duplication is avoided here by only creating one instance of the references - the hyperlinks on each module API page will redirect to the references.rst section.
-  the list of the references would no longer be on each API page - replaced by a simple link, using [cross-referencing](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#getting-started)
- there is a warning generated about the references.rst not being in any 'toctree' which might need to be resolved 

Do you have a preference either way?

**Comment by jwallwork23** [comment]
Thanks for looking into this @acse-ej321. The second approach sounds better to me.
